apiVersion: cloudshell.cloudtty.io/v1alpha1
kind: CloudShell
metadata:
  name: cloudshell-sample
spec:
  secretRef:
    name: "my-kubeconfig"
  commandAction: "bash"
  ttl: 500
  once: false
  image: release-ci.daocloud.io/cloudtty/cloudshell:v0.6.0
