apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudtty.controllerManager.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 52a02cd6.cloudtty.io
