name: Build & Release Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            VERSION=latest
          fi
          echo ::set-output name=VERSION::${VERSION}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Make 
        run: |
              make docker-build
              #make build-chart
      - name: Push 
        run: |
              make docker-push
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
      - name: Build & Pushing cloudshell image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile-webtty
          labels: |-
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          #push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: |-
             ghcr.io/cloudtty/cloudshell:${{ steps.get_version.outputs.VERSION }}
      - name: Build & Pushing operator image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          labels: |-
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          #push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: |-
             ghcr.io/cloudtty/cloudshell-operator:${{ steps.get_version.outputs.VERSION }}

